export const INCREMENT_VALUE = 'INCREMENT_VALUE';
export const DECREMENT_VALUE = 'DECREMENT_VALUE';

export const START_LOGIN = 'START_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAIL_LOGIN = 'FAIL_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const FINISH_LOGOUT = 'FINISH_LOGOUT';

export const CATEGORY_REQUEST = 'CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED';

export const ALBUMS_REQUEST = 'ALBUMS_REQUEST';
export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAILED = 'GET_ALBUMS_FAILED';

export const SINGERS_REQUEST = 'SINGERS_REQUEST';
export const GET_SINGERS_SUCCESS = 'GET_SINGERS_SUCCESS';
export const GET_SINGERS_FAILED = 'GET_SINGERS_FAILED';

export const SONGS_REQUEST = 'SONGS_REQUEST';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';
export const GET_SONGS_FAILED = 'GET_SONGS_FAILED';

export const USERS_REQUEST = 'USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED'; 